name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    # container:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LÖVE
        run: |
          sudo add-apt-repository ppa:bartbes/love-stable -y
          sudo apt-get update
          sudo apt-get install -y love

      - name: Verify LÖVE
        run: love --version

      - name: Run Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luacheck
          luacheck . --no-color -q
        continue-on-error: true
